working with intel 2023.2

diff --git a/Mpi4py/install b/Mpi4py/install
--- a/Mpi4py/install
+++ b/Mpi4py/install
@@ -33,4 +33,17 @@ python3 setup.py install --prefix="$INSTALLPATH"
 
 # Test installation
 # kpython -n 2 -t 1 test/t1.py
+
+echo "Testing Mpi4py installation with mpirun..."
+
+mpirun --version
+
+mpirun -n 2 python3 test/t1.py
+
+# Check if mpirun was successful
+if [ $? -ne 0 ]; then
+    echo "Mpi4py test failed. Aborting."
+    exit 1
+fi
+
 echo "Mpi4py correctly installed."
